# Generated by Django 6.0.3 on 2026-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaaydeuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
